vich_uploader:
  db_driver: orm

  mappings:
     producer_image:
        uri_prefix: /images/producers
        upload_destination: '%kernel.project_dir%/public/images/producers'
        namer: Vich\UploaderBundle\Naming\UniqidNamer
     good_image:
       uri_prefix: /images/goods
       upload_destination: '%kernel.project_dir%/public/images/goods'
       namer: Vich\UploaderBundle\Naming\UniqidNamer
